### ISSUE TITLE
Fix VLabs Related Links in Template

### ISSUE THREAD

**Issue by palutlaanirudh** [mushie101/Assignment4_Ass4#4]
Multiple VLabs related lead to the wrong page or are broken, namely:
- Community
- FAQ
- Home
- All Labs
- Partners
- Contact
- Virtual Labs 
- LinkedIn icon
- All links under updates
Fix in the `temp.html` file.

**Comment by palutlaanirudh** [comment]
Unnecessary but optional fixes according to the TA. Fix if we have the time.

**Comment by mushie101** [comment]
this done?
